// Generates public/data/wolfe-rankings.json from wolfe-ranked-list.md
// Run: node scripts/buildWolfeData.js

const fs = require('fs');
const path = require('path');

const pokemon = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../data/pokemon.json'))
);

// Build lookup maps
const byName = {};
pokemon.forEach(p => { byName[p.name.toLowerCase()] = p; });

// Explicit overrides: wolfe list name → pokemon id
// Handles regional forms, renamed forms, garbled names, etc.
const OVERRIDES = {
  // Regional forms (wolfe uses "Alolan/Galarian/Hisuian/Paldean Foo Form")
  'rattata alolan form':               10091,
  'raticate alolan form':              10092,
  'raichu alolan form':                10100,
  'sandshrew alolan form':             10101,
  'sandslash alolan form':             10102,
  'vulpix alolan form':                10103,
  'ninetales alolan form':             10104,
  'diglett alolan form':               10105,
  'dugtrio alolan form':               10106,
  'meowth alolan form':                10107,
  'meowth galarian form':              10161,
  'persian alolan form':               10108,
  'growlithe hisuian form':            10229,
  'arcanine hisuian form':             10230,
  'geodude alolan form':               10109,
  'graveler alolan form':              10110,
  'golem alolan form':                 10111,
  'ponyta galarian form':              10162,
  'rapidash galarian form':            10163,
  'slowpoke galarian form':            10164,
  'slowbro galarian form':             10165,
  "farfetch'd galarian form":          10166,
  'grimer alolan form':                10112,
  'muk alolan form':                   10113,
  'voltorb hisuian form':              10231,
  'electrode hisuian form':            10232,
  'exeggutor alolan form':             10114,
  'marowak alolan form':               10115,
  'weezing galarian form':             10167,
  'mr. mime galarian form':            10168,
  'tauros paldean combat breed':       10250,
  'tauros paldean blaze breed':        10251,
  'tauros paldean aqua breed':         10252,
  'articuno galarian form':            10169,
  'zapdos galarian form':              10170,
  'moltres galarian form':             10171,
  'typhlosion hisuian form':           10233,
  'wooper paldean form':               10253,
  'slowking galarian form':            10172,
  'qwilfish hisuian form':             10234,
  'sneasel hisuian form':              10235,
  'corsola galarian form':             10173,
  'zigzagoon galarian form':           10174,
  'linoone galarian form':             10175,
  'darumaka galarian form':            10176,
  'darmanitan galarian form':          10177,
  'yamask galarian form':              10179,
  'zorua hisuian form':                10238,
  'zoroark hisuian form':              10239,
  'stunfisk galarian form':            10180,
  'braviary hisuian form':             10240,
  'sliggoo hisuian form':              10241,
  'goodra hisuian form':               10242,
  'avalugg hisuian form':              10243,
  'decidueye hisuian form':            10244,
  'samurott hisuian form':             10236,
  'lilligant hisuian form':            10237,
  // Non-regional forms
  'dialga origin form':                10245,
  'palkia origin form':                10246,
  'kyurem black form':                 10022,
  'kyurem white form':                 10023,
  'tornadus therian form':             10019,
  'thundurus therian form':            10020,
  'landorus therian form':             10021,
  'landorus incarnate form':           645,
  'tornadus incarnate form':           641,
  'thundurus incarnate form':          642,
  'enamorus incarnate form':           905,
  'enamorus therian form':             10249,
  'deoxys attack form':                10001,
  'deoxys defense form':               10002,
  'deoxys speed form':                 10003,
  'deoxys normal form':                386,
  'necrozma dusk mane':                10155,
  'necrozma dawn wings':               10156,
  'calyrex ice rider':                 10193,
  'calyrex shadow rider':              10194,
  'calyrex':                           898,
  'oricorio baile style':              741,
  "oricorio pa'u style":               10124,
  'oricorio pom-pom style':            10123,
  'oricorio sensu style':              10125,
  'lycanroc midnight form':            10126,
  'lycanroc dusk form':                10152,
  'lycanroc midday form':              745,
  'necrozma':                          800,
  'giratina altered form':             487,
  'giratina origin form':              10244, // wait - giratina origin is a diff id
  'wishiwashi school form':            10127,
  'wishiwashi':                        10127, // wolfe ranks the school form
  'zygarde 50% form':                  718,
  'zygarde 10% form':                  10181,
  'zygarde complete form':             10120,
  'hoopa confined':                    720,
  'hoopa unbound':                     10086,
  'meowstic male':                     678,
  'meowstic female':                   10025,
  'indeedee male':                     876,
  'indeedee female':                   10186,
  'urshifu single strike style':       892,
  'urshifu rapid strike style':        10191,
  'ursaluna bloodmoon form':           10272,
  'basculegion male':                  902,
  'basculegion female':                10248,
  'oinkologne male':                   916,
  'oinkologne female':                 10254,
  'ogerpon teal mask':                 1017,
  'ogerpon wellspring mask':           10273,
  'ogerpon hearthflame mask':          10274,
  'ogerpon cornerstone mask':          10275,
  'keldeo ordinary form':              647,
  'keldeo resolute form':              10024,
  'shaymin land form':                 492,
  'shaymin sky form':                  10006,
  'meloetta aria form':                648,
  'rotom':                             479,
  'rotom heat form':                   10008,
  'rotom wash form':                   10009,
  'rotom frost form':                  10010,
  'rotom fan form':                    10011,
  'rotom mow form':                    10012,
  'castform normal form':              351,
  'castform sunny form':               10013,
  'castform rainy form':               10014,
  'castform snowy form':               10015,
  'basculin red/blue stripe':          550,
  'basculin-white-striped':            10247,
  'basculin white-striped':            10247,
  'shellos west sea':                  422,
  'shellos east sea':                  10039,
  'gastrodon west sea':                423,
  'gastrodon east sea':                10040,
  'burmy plant cloak':                 412,
  'burmy sandy cloak':                 10034,
  'burmy trash cloak':                 10035,
  'wormadam plant cloak':              413,
  'wormadam sandy cloak':              10004,
  'wormadam trash cloak':              10005,
  'tauros kanto form':                 128,
  'florges (all forms)':               671,
  'floette (all flower forms)':        670,
  'unown (all forms)':                 201,
  'alcremie (all forms)':              869,
  'vivillon (all forms)':              666,
  'florges all forms':                 671,
  'floette all flower forms':          670,
  'unown all forms':                   201,
  'alcremie all forms':                869,
  'vivillon all forms':                666,
  // Giratina Origin — correct ID
  'giratina origin form':              10007,
};


// The full wolfe ranked list: [rank, name, category]
// Derived from wolfe-ranked-list.md
const WOLFE_LIST = [
  // Pre-category
  [1133, 'Rellor', 'Pre-Category'],
  [1132, 'Barbaracle', 'Pre-Category'],
  [1131, 'Ledyba', 'Pre-Category'],
  // True Fodder
  [1130, 'Binacle', 'True Fodder'],
  [1129, 'Ledian', 'True Fodder'],
  [1128, 'Gossifleur', 'True Fodder'],
  [1127, 'Klink', 'True Fodder'],
  [1126, 'Mothim', 'True Fodder'],
  [1125, 'Tympole', 'True Fodder'],
  [1124, 'Diglett Alolan Form', 'True Fodder'],
  [1123, 'Cherubi', 'True Fodder'],
  [1122, 'Smoochum', 'True Fodder'],
  [1121, 'Gumshoos', 'True Fodder'],
  [1120, 'Geodude Alolan Form', 'True Fodder'],
  [1119, 'Skwovet', 'True Fodder'],
  [1118, 'Pineco', 'True Fodder'],
  [1117, 'Patrat', 'True Fodder'],
  [1116, 'Tranquill', 'True Fodder'],
  [1115, 'Capsakid', 'True Fodder'],
  [1114, 'Sunkern', 'True Fodder'],
  [1113, 'Spinarak', 'True Fodder'],
  [1112, 'Burmy Plant Cloak', 'True Fodder'],
  [1111, 'Burmy Sandy Cloak', 'True Fodder'],
  [1110, 'Wormadam Plant Cloak', 'True Fodder'],
  [1109, 'Wormadam Sandy Cloak', 'True Fodder'],
  [1108, 'Bunnelby', 'True Fodder'],
  [1107, 'Shroodle', 'True Fodder'],
  [1106, 'Carnivine', 'True Fodder'],
  [1105, 'Nymble', 'True Fodder'],
  [1104, 'Wugtrio', 'True Fodder'],
  [1103, 'Sandshrew Alolan Form', 'True Fodder'],
  [1102, 'Seedot', 'True Fodder'],
  [1101, 'Nincada', 'True Fodder'],
  [1100, 'Heatmor', 'True Fodder'],
  [1099, 'Bounsweet', 'True Fodder'],
  [1098, 'Tyrogue', 'True Fodder'],
  [1097, 'Cufant', 'True Fodder'],
  [1096, 'Maschiff', 'True Fodder'],
  [1095, 'Bergmite', 'True Fodder'],
  [1094, 'Morelull', 'True Fodder'],
  [1093, 'Grubbin', 'True Fodder'],
  [1092, 'Chingling', 'True Fodder'],
  [1091, 'Karrablast', 'True Fodder'],
  [1090, 'Spritzee', 'True Fodder'],
  [1089, 'Fomantis', 'True Fodder'],
  [1088, 'Spearow', 'True Fodder'],
  [1087, 'Wiglett', 'True Fodder'],
  [1086, 'Trumbeak', 'True Fodder'],
  [1085, 'Remoraid', 'True Fodder'],
  [1084, 'Alomomola', 'True Fodder'],
  [1083, 'Elgyem', 'True Fodder'],
  [1082, 'Chewtle', 'True Fodder'],
  [1081, 'Arrokuda', 'True Fodder'],
  [1080, 'Watchog', 'True Fodder'],
  [1079, 'Mantyke', 'True Fodder'],
  [1078, 'Grumpig', 'True Fodder'],
  [1077, 'Nidoran♂', 'True Fodder'],
  [1076, 'Nidoran♀', 'True Fodder'],
  [1075, 'Surskit', 'True Fodder'],
  [1074, 'Finneon', 'True Fodder'],
  [1073, 'Dwebble', 'True Fodder'],
  [1072, 'Yungoos', 'True Fodder'],
  // Badge Collectors
  [1071, 'Klang', 'Badge Collectors'],
  [1070, 'Quilladin', 'Badge Collectors'],
  [1069, 'Blipbug', 'Badge Collectors'],
  [1068, 'Clobbopus', 'Badge Collectors'],
  [1067, 'Meditite', 'Badge Collectors'],
  [1066, 'Stunky', 'Badge Collectors'],
  [1065, 'Basculin Red/Blue Stripe', 'Badge Collectors'],
  [1064, 'Shiinotic', 'Badge Collectors'],
  [1063, 'Graveler Alolan Form', 'Badge Collectors'],
  [1062, 'Slugma', 'Badge Collectors'],
  [1061, 'Nuzleaf', 'Badge Collectors'],
  [1060, 'Masquerain', 'Badge Collectors'],
  [1059, 'Electrike', 'Badge Collectors'],
  [1058, 'Snorunt', 'Badge Collectors'],
  [1057, 'Kricketot', 'Badge Collectors'],
  [1056, 'Burmy Trash Cloak', 'Badge Collectors'],
  [1055, 'Wormadam Trash Cloak', 'Badge Collectors'],
  [1054, 'Glameow', 'Badge Collectors'],
  [1053, 'Maractus', 'Badge Collectors'],
  [1052, 'Ducklett', 'Badge Collectors'],
  [1051, 'Tynamo', 'Badge Collectors'],
  [1050, 'Cubchoo', 'Badge Collectors'],
  [1049, 'Skiddo', 'Badge Collectors'],
  [1048, 'Pancham', 'Badge Collectors'],
  [1047, 'Crabrawler', 'Badge Collectors'],
  [1046, 'Mareanie', 'Badge Collectors'],
  [1045, 'Grapploct', 'Badge Collectors'],
  [1044, 'Tadbulb', 'Badge Collectors'],
  [1043, 'Ariados', 'Badge Collectors'],
  [1042, 'Snubbull', 'Badge Collectors'],
  [1041, 'Granbull', 'Badge Collectors'],
  [1040, 'Gulpin', 'Badge Collectors'],
  [1039, 'Barboach', 'Badge Collectors'],
  [1038, 'Silicobra', 'Badge Collectors'],
  [1037, 'Oinkologne Female', 'Badge Collectors'],
  [1036, 'Weedle', 'Badge Collectors'],
  [1035, 'Raticate', 'Badge Collectors'],
  [1034, 'Fearow', 'Badge Collectors'],
  [1033, 'Dugtrio Alolan Form', 'Badge Collectors'],
  [1032, 'Mankey', 'Badge Collectors'],
  [1031, 'Hypno', 'Badge Collectors'],
  [1030, 'Hoothoot', 'Badge Collectors'],
  [1029, 'Silcoon', 'Badge Collectors'],
  [1028, 'Cascoon', 'Badge Collectors'],
  [1027, 'Whismur', 'Badge Collectors'],
  [1026, 'Nosepass', 'Badge Collectors'],
  [1025, 'Aron', 'Badge Collectors'],
  [1024, 'Luvdisc', 'Badge Collectors'],
  [1023, 'Skorupi', 'Badge Collectors'],
  [1022, 'Pidove', 'Badge Collectors'],
  [1021, 'Palpitoad', 'Badge Collectors'],
  [1020, 'Shelmet', 'Badge Collectors'],
  [1019, 'Chespin', 'Badge Collectors'],
  [1018, 'Helioptile', 'Badge Collectors'],
  [1017, 'Steenee', 'Badge Collectors'],
  [1016, 'Drizzile', 'Badge Collectors'],
  [1015, 'Rolycoly', 'Badge Collectors'],
  [1014, 'Milcery', 'Badge Collectors'],
  [1013, 'Flittle', 'Badge Collectors'], // implied rank — not explicitly numbered in transcript
  [1012, 'Sunflora', 'Badge Collectors'],
  [1011, 'Stantler', 'Badge Collectors'],
  [1010, 'Carkol', 'Badge Collectors'],
  [1009, 'Oinkologne Male', 'Badge Collectors'],
  [1008, 'Kakuna', 'Badge Collectors'],
  [1007, 'Raticate Alolan Form', 'Badge Collectors'],
  [1006, 'Sandshrew', 'Badge Collectors'],
  [1005, 'Nidorina', 'Badge Collectors'],
  [1004, 'Nidorino', 'Badge Collectors'],
  [1003, 'Geodude', 'Badge Collectors'],
  [1002, 'Grimer', 'Badge Collectors'],
  [1001, 'Krabby', 'Badge Collectors'],
  [1000, 'Chinchou', 'Badge Collectors'],
  [999, 'Natu', 'Badge Collectors'],
  [998, 'Magcargo', 'Badge Collectors'],
  [997, 'Octillery', 'Badge Collectors'],
  [996, 'Donphan', 'Badge Collectors'],
  [995, 'Slakoth', 'Badge Collectors'],
  [994, 'Ninjask', 'Badge Collectors'],
  [993, 'Baltoy', 'Badge Collectors'],
  // Trailer Filler
  [992, 'Klinklang', 'Trailer Filler'],
  [991, 'Spidops', 'Trailer Filler'],
  [990, 'Woobat', 'Trailer Filler'],
  [989, 'Scatterbug', 'Trailer Filler'],
  [988, 'Tyrunt', 'Trailer Filler'],
  [987, 'Sandygast', 'Trailer Filler'],
  [986, 'Minior', 'Trailer Filler'],
  [985, 'Greedent', 'Trailer Filler'],
  [984, 'Litleo', 'Trailer Filler'],
  [983, 'Rookidee', 'Trailer Filler'],
  [982, 'Dottler', 'Trailer Filler'],
  [981, 'Quaxwell', 'Trailer Filler'],
  [980, 'Frigibax', 'Trailer Filler'],
  [979, 'Varoom', 'Trailer Filler'],
  [978, 'Houndour', 'Trailer Filler'],
  [977, 'Impidimp', 'Trailer Filler'],
  [976, 'Spoink', 'Trailer Filler'],
  [975, 'Timburr', 'Trailer Filler'],
  [974, 'Throh', 'Trailer Filler'],
  [973, 'Bruxish', 'Trailer Filler'],
  [972, 'Thievul', 'Trailer Filler'],
  [971, 'Budew', 'Trailer Filler'],
  [970, 'Azurill', 'Trailer Filler'],
  [969, 'Pupitar', 'Trailer Filler'],
  [968, 'Rattata', 'Trailer Filler'],
  [967, 'Sandslash Alolan Form', 'Trailer Filler'],
  [966, 'Sentret', 'Trailer Filler'],
  [965, 'Skiploom', 'Trailer Filler'],
  [964, 'Wurmple', 'Trailer Filler'],
  [963, 'Loudred', 'Trailer Filler'],
  [962, 'Shuppet', 'Trailer Filler'],
  [961, 'Glalie', 'Trailer Filler'],
  [960, 'Combee', 'Trailer Filler'],
  [959, 'Happiny', 'Trailer Filler'],
  [958, 'Pignite', 'Trailer Filler'],
  // Almost Worth Remembering
  [957, 'Unfezant', 'Almost Worth Remembering'],
  [956, 'Jangmo-o', 'Almost Worth Remembering'],
  [955, 'Veluza', 'Almost Worth Remembering'],
  [954, 'Flabébé', 'Almost Worth Remembering'],
  [953, 'Swirlix', 'Almost Worth Remembering'],
  [952, 'Swoobat', 'Almost Worth Remembering'],
  [951, 'Swanna', 'Almost Worth Remembering'],
  [950, 'Bouffalant', 'Almost Worth Remembering'],
  [949, 'Pangoro', 'Almost Worth Remembering'],
  [948, 'Skrelp', 'Almost Worth Remembering'],
  [947, 'Pikipek', 'Almost Worth Remembering'],
  [946, 'Wimpod', 'Almost Worth Remembering'],
  [945, 'Corvisquire', 'Almost Worth Remembering'],
  [944, 'Nickit', 'Almost Worth Remembering'],
  [943, 'Copperajah', 'Almost Worth Remembering'],
  [942, 'Tinkatink', 'Almost Worth Remembering'],
  [941, 'Igglybuff', 'Almost Worth Remembering'],
  [940, 'Swinub', 'Almost Worth Remembering'],
  [939, 'Boltund', 'Almost Worth Remembering'],
  [938, 'Bombirdier', 'Almost Worth Remembering'],
  [937, 'Linoone Galarian Form', 'Almost Worth Remembering'],
  [936, 'Numel', 'Almost Worth Remembering'],
  [935, 'Yamask', 'Almost Worth Remembering'],
  [934, 'Yamask Galarian Form', 'Almost Worth Remembering'],
  [933, 'Carbink', 'Almost Worth Remembering'],
  [932, 'Bramblin', 'Almost Worth Remembering'],
  [931, 'Volcanion', 'Almost Worth Remembering'],
  // Featured in an Anime Episode
  [930, 'Metapod', 'Featured in an Anime Episode'],
  [929, 'Cosmoem', 'Featured in an Anime Episode'],
  [928, 'Frillish', 'Featured in an Anime Episode'],
  [927, 'Carvanha', 'Featured in an Anime Episode'],
  [926, 'Zarude', 'Featured in an Anime Episode'],
  [925, 'Poliwag', 'Featured in an Anime Episode'],
  [924, 'Corphish', 'Featured in an Anime Episode'],
  [923, 'Machop', 'Featured in an Anime Episode'],
  [922, 'Graveler', 'Featured in an Anime Episode'],
  [921, 'Doduo', 'Featured in an Anime Episode'],
  [920, 'Mr. Mime Galarian Form', 'Featured in an Anime Episode'],
  [919, 'Shroomish', 'Featured in an Anime Episode'],
  [918, 'Anorith', 'Featured in an Anime Episode'],
  [917, 'Buneary', 'Featured in an Anime Episode'],
  [916, 'Lickilicky', 'Featured in an Anime Episode'],
  [915, 'Lillipup', 'Featured in an Anime Episode'],
  [914, 'Roggenrola', 'Featured in an Anime Episode'],
  [913, 'Venipede', 'Featured in an Anime Episode'],
  [912, 'Druddigon', 'Featured in an Anime Episode'],
  [911, 'Phantump', 'Featured in an Anime Episode'],
  [910, 'Salandit', 'Featured in an Anime Episode'],
  [909, 'Dubwool', 'Featured in an Anime Episode'],
  [908, 'Dolliv', 'Featured in an Anime Episode'],
  [907, 'Charcadet', 'Featured in an Anime Episode'],
  [906, 'Aipom', 'Featured in an Anime Episode'],
  [905, 'Mime Jr.', 'Featured in an Anime Episode'],
  [904, 'Qwilfish', 'Featured in an Anime Episode'],
  [903, 'Beautifly', 'Featured in an Anime Episode'],
  [902, 'Cacnea', 'Featured in an Anime Episode'],
  [901, 'Munna', 'Featured in an Anime Episode'],
  [900, 'Corsola Galarian Form', 'Featured in an Anime Episode'],
  [899, 'Hakamo-o', 'Featured in an Anime Episode'],
  [898, 'Naclstack', 'Featured in an Anime Episode'],
  [897, 'Wattrel', 'Featured in an Anime Episode'],
  [896, 'Cetoddle', 'Featured in an Anime Episode'],
  [895, 'Sandslash', 'Featured in an Anime Episode'],
  [894, 'Drowzee', 'Featured in an Anime Episode'],
  // Usable (Derogatory)
  [893, 'Forretress', 'Usable (Derogatory)'],
  [892, 'Ursaring', 'Usable (Derogatory)'],
  [891, 'Phanpy', 'Usable (Derogatory)'],
  [890, 'Magby', 'Usable (Derogatory)'],
  [889, 'Gogoat', 'Usable (Derogatory)'],
  [888, 'Piloswine', 'Usable (Derogatory)'],
  [887, 'Lombre', 'Usable (Derogatory)'],
  [886, 'Beheeyem', 'Usable (Derogatory)'],
  [885, 'Vigoroth', 'Usable (Derogatory)'],
  [884, 'Swalot', 'Usable (Derogatory)'],
  [883, 'Wynaut', 'Usable (Derogatory)'],
  [882, 'Huntail', 'Usable (Derogatory)'],
  [881, 'Lechonk', 'Usable (Derogatory)'],
  [880, 'Shieldon', 'Usable (Derogatory)'],
  [879, 'Gorebyss', 'Usable (Derogatory)'],
  [878, 'Phione', 'Usable (Derogatory)'],
  [877, 'Blitzle', 'Usable (Derogatory)'],
  [876, 'Vanillite', 'Usable (Derogatory)'],
  [875, 'Clauncher', 'Usable (Derogatory)'],
  [874, 'Dedenne', 'Usable (Derogatory)'],
  [873, 'Pumpkaboo', 'Usable (Derogatory)'],
  [872, 'Hisuian Avalugg', 'Usable (Derogatory)'],
  [871, 'Crabominable', 'Usable (Derogatory)'],
  [870, 'Mudbray', 'Usable (Derogatory)'],
  [869, 'Stufful', 'Usable (Derogatory)'],
  [868, 'Meltan', 'Usable (Derogatory)'],
  [867, 'Toxel', 'Usable (Derogatory)'],
  [866, 'Sinistea', 'Usable (Derogatory)'],
  [865, 'Probopass', 'Usable (Derogatory)'],
  [864, 'Morgrem', 'Usable (Derogatory)'],
  [863, 'Kubfu', 'Usable (Derogatory)'],
  [862, 'Squawkabilly', 'Usable (Derogatory)'],
  [861, 'Arctibax', 'Usable (Derogatory)'],
  [860, 'Avalugg', 'Usable (Derogatory)'],
  [859, 'Simisear', 'Usable (Derogatory)'],
  [858, 'Gligar', 'Usable (Derogatory)'],
  // Fool's Gold
  [857, 'Mantine', "Fool's Gold"],
  [856, 'Skuntank', "Fool's Gold"],
  [855, 'Cherrim', "Fool's Gold"],
  [854, 'Clamperl', "Fool's Gold"],
  [853, 'Snover', "Fool's Gold"],
  [852, 'Tirtouga', "Fool's Gold"],
  [851, 'Solosis', "Fool's Gold"],
  [850, 'Pidgey', "Fool's Gold"],
  [849, 'Rattata Alolan Form', "Fool's Gold"],
  [848, 'Venomoth', "Fool's Gold"],
  [847, 'Exeggcute', "Fool's Gold"],
  [846, 'Miltank', "Fool's Gold"],
  [845, 'Noctowl', "Fool's Gold"],
  [844, 'Golem Alolan Form', "Fool's Gold"],
  [843, 'Ponyta Galarian Form', "Fool's Gold"],
  [842, 'Dustox', "Fool's Gold"],
  [841, 'Seel', "Fool's Gold"],
  [840, 'Lickitung', "Fool's Gold"],
  [839, 'Croconaw', "Fool's Gold"],
  [838, 'Girafarig', "Fool's Gold"],
  [837, 'Teddiursa', "Fool's Gold"],
  [836, 'Corsola', "Fool's Gold"],
  [835, 'Pyukumuku', "Fool's Gold"],
  [834, 'Zigzagoon Galarian Form', "Fool's Gold"],
  [833, 'Lotad', "Fool's Gold"],
  [832, 'Makuhita', "Fool's Gold"],
  [831, 'Lairon', "Fool's Gold"],
  [830, 'Whiscash', "Fool's Gold"],
  [829, 'Starly', "Fool's Gold"],
  [828, 'Ambipom', "Fool's Gold"],
  [827, 'Herdier', "Fool's Gold"],
  [826, 'Boldore', "Fool's Gold"],
  [825, 'Petilil', "Fool's Gold"],
  [824, 'Gothita', "Fool's Gold"],
  [823, 'Deerling', "Fool's Gold"],
  [822, 'Sawsbuck', "Fool's Gold"],
  [821, 'Eelektrik', "Fool's Gold"],
  [820, 'Beartic', "Fool's Gold"],
  [819, 'Golett', "Fool's Gold"],
  [818, 'Diggersby', "Fool's Gold"],
  [817, 'Inkay', "Fool's Gold"],
  [816, 'Poipole', "Fool's Gold"],
  [815, 'Simipour', "Fool's Gold"],
  // Worth a Thought, Extremely Ugly
  [814, 'Barraskewda', 'Worth a Thought, Extremely Ugly'],
  [813, 'Sizzlipede', 'Worth a Thought, Extremely Ugly'],
  [812, 'Dhelmise', 'Worth a Thought, Extremely Ugly'],
  [811, 'Perrserker', 'Worth a Thought, Extremely Ugly'],
  [810, 'Tarountula', 'Worth a Thought, Extremely Ugly'],
  [809, 'Gimmighoul', 'Worth a Thought, Extremely Ugly'],
  [808, 'Stonjourner', 'Worth a Thought, Extremely Ugly'],
  [807, 'Pansear', 'Worth a Thought, Extremely Ugly'],
  [806, 'Dunsparce', 'Worth a Thought, Extremely Ugly'],
  [805, 'Hisuian Qwilfish', 'Worth a Thought, Extremely Ugly'],
  [804, 'Panpour', 'Worth a Thought, Extremely Ugly'],
  [803, 'Exploud', 'Worth a Thought, Extremely Ugly'],
  [802, 'Cranidos', 'Worth a Thought, Extremely Ugly'],
  [801, 'Purugly', 'Worth a Thought, Extremely Ugly'],
  [800, 'Pansage', 'Worth a Thought, Extremely Ugly'],
  [799, 'Ferroseed', 'Worth a Thought, Extremely Ugly'],
  [798, 'Tyrantrum', 'Worth a Thought, Extremely Ugly'],
  [797, 'Pyroar', 'Worth a Thought, Extremely Ugly'],
  [796, 'Xatu', 'Worth a Thought, Extremely Ugly'],
  [795, 'Claydol', 'Worth a Thought, Extremely Ugly'],
  [794, 'Chimecho', 'Worth a Thought, Extremely Ugly'],
  [793, 'Rapidash Galarian Form', 'Worth a Thought, Extremely Ugly'],
  [792, 'Machoke', 'Worth a Thought, Extremely Ugly'],
  [791, 'Kingler', 'Worth a Thought, Extremely Ugly'],
  [790, 'Primeape', 'Worth a Thought, Extremely Ugly'],
  [789, 'Dodrio', 'Worth a Thought, Extremely Ugly'],
  [788, 'Hitmonchan', 'Worth a Thought, Extremely Ugly'],
  [787, 'Delibird', 'Worth a Thought, Extremely Ugly'],
  [786, 'Larvitar', 'Worth a Thought, Extremely Ugly'],
  [785, 'Unown (all forms)', 'Worth a Thought, Extremely Ugly'],
  // Here to Look Good
  [784, 'Floette (all flower forms)', 'Here to Look Good'],
  [783, 'Sawk', 'Here to Look Good'],
  [782, 'Grafaiai', 'Here to Look Good'],
  [781, 'Frafure', 'Here to Look Good'],
  [780, 'Volbeat', 'Here to Look Good'],
  [779, 'Illumise', 'Here to Look Good'],
  [778, 'Wailmer', 'Here to Look Good'],
  [777, 'Swablu', 'Here to Look Good'],
  [776, 'Castform Normal Form', 'Here to Look Good'],
  [775, 'Castform Snowy Form', 'Here to Look Good'],
  [774, 'Castform Sunny Form', 'Here to Look Good'],
  [773, 'Castform Rainy Form', 'Here to Look Good'],
  [772, 'Skitty', 'Here to Look Good'],
  [771, 'Bonsly', 'Here to Look Good'],
  [770, 'Chatot', 'Here to Look Good'],
  [769, 'Basculin White-Striped', 'Here to Look Good'],
  [768, 'Fletchling', 'Here to Look Good'],
  [767, 'Honedge', 'Here to Look Good'],
  [766, 'Heliolisk', 'Here to Look Good'],
  [765, 'Amaura', 'Here to Look Good'],
  [764, 'Dartrix', 'Here to Look Good'],
  [763, 'Turtonator', 'Here to Look Good'],
  [762, 'Sobble', 'Here to Look Good'],
  [761, 'Yamper', 'Here to Look Good'],
  [760, 'Smoliv', 'Here to Look Good'],
  [759, 'Klawf', 'Here to Look Good'],
  [758, 'Pidgeotto', 'Here to Look Good'],
  [757, 'Lanturn', 'Here to Look Good'],
  [756, 'Munkidori', 'Here to Look Good'],
  [755, 'Passimian', 'Here to Look Good'],
  [754, 'Houndoom', 'Here to Look Good'],
  [753, 'Crocalor', 'Here to Look Good'],
  [752, 'Poochyena', 'Here to Look Good'],
  [751, 'Linoone', 'Here to Look Good'],
  [750, 'Armaldo', 'Here to Look Good'],
  [749, 'Fletchinder', 'Here to Look Good'],
  [748, 'Dipplin', 'Here to Look Good'],
  [747, 'Simisage', 'Here to Look Good'],
  [746, 'Bellsprout', 'Here to Look Good'],
  [745, 'Golem', 'Here to Look Good'],
  [744, 'Ponyta', 'Here to Look Good'],
  [743, 'Grimer Alolan Form', 'Here to Look Good'],
  [742, 'Muk', 'Here to Look Good'],
  [741, 'Voltorb Hisuian Form', 'Here to Look Good'],
  [740, 'Goldeen', 'Here to Look Good'],
  [739, 'Seaking', 'Here to Look Good'],
  [738, 'Chikorita', 'Here to Look Good'],
  [737, 'Totodile', 'Here to Look Good'],
  [736, 'Combusken', 'Here to Look Good'],
  [735, 'Taillow', 'Here to Look Good'],
  [734, 'Spinda', 'Here to Look Good'],
  [733, 'Vibrava', 'Here to Look Good'],
  [732, 'Lileep', 'Here to Look Good'],
  [731, 'Shinx', 'Here to Look Good'],
  [730, 'Lumineon', 'Here to Look Good'],
  [729, 'Gurdurr', 'Here to Look Good'],
  [728, 'Sewaddle', 'Here to Look Good'],
  [727, 'Whirlipede', 'Here to Look Good'],
  [726, 'Axew', 'Here to Look Good'],
  [725, 'Fennekin', 'Here to Look Good'],
  [724, 'Oddish', 'Here to Look Good'],
  [723, 'Froakie', 'Here to Look Good'],
  [722, 'Frogadier', 'Here to Look Good'],
  [721, 'Furfrou', 'Here to Look Good'],
  // Round Nine Draft Picks
  [720, 'Toucannon', 'Round Nine Draft Picks'],
  [719, 'Meowstic Female', 'Round Nine Draft Picks'],
  [718, 'Aromatisse', 'Round Nine Draft Picks'],
  [717, 'Noibat', 'Round Nine Draft Picks'],
  [716, 'Cursola', 'Round Nine Draft Picks'],
  [715, 'Charjabug', 'Round Nine Draft Picks'],
  [714, 'Palossand', 'Round Nine Draft Picks'],
  [713, 'Finizen', 'Round Nine Draft Picks'],
  [712, 'Eldegoss', 'Round Nine Draft Picks'],
  [711, 'Applin', 'Round Nine Draft Picks'],
  [710, 'Hattenna', 'Round Nine Draft Picks'],
  [709, 'Pawmi', 'Round Nine Draft Picks'],
  [708, 'Fidough', 'Round Nine Draft Picks'],
  [707, 'Nacli', 'Round Nine Draft Picks'],
  [706, 'Minun', 'Round Nine Draft Picks'],
  [705, 'Plusle', 'Round Nine Draft Picks'],
  [704, 'Shellder', 'Round Nine Draft Picks'],
  [703, 'Hoppip', 'Round Nine Draft Picks'],
  [702, 'Zangoose', 'Round Nine Draft Picks'],
  [701, 'Abra', 'Round Nine Draft Picks'],
  [700, 'Duskull', 'Round Nine Draft Picks'],
  [699, 'Hippopotas', 'Round Nine Draft Picks'],
  [698, 'Crustle', 'Round Nine Draft Picks'],
  [697, 'Mabosstiff', 'Round Nine Draft Picks'],
  [696, 'Glimmet', 'Round Nine Draft Picks'],
  [695, 'Pincurchin', 'Round Nine Draft Picks'],
  [694, 'Shellos West Sea', 'Round Nine Draft Picks'],
  [693, 'Dusknoir', 'Round Nine Draft Picks'],
  [692, 'Komala', 'Round Nine Draft Picks'],
  [691, 'Rockruff', 'Round Nine Draft Picks'],
  [690, 'Solrock', 'Round Nine Draft Picks'],
  [689, 'Falinks', 'Round Nine Draft Picks'],
  [688, 'Lunatone', 'Round Nine Draft Picks'],
  [687, 'Servine', 'Round Nine Draft Picks'],
  [686, 'Ekans', 'Round Nine Draft Picks'],
  [685, 'Zebstrika', 'Round Nine Draft Picks'],
  [684, 'Gloom', 'Round Nine Draft Picks'],
  [683, 'Diglett', 'Round Nine Draft Picks'],
  [682, 'Weepinbell', 'Round Nine Draft Picks'],
  [681, 'Magnemite', 'Round Nine Draft Picks'],
  [680, 'Bayleef', 'Round Nine Draft Picks'],
  [679, 'Yanma', 'Round Nine Draft Picks'],
  [678, 'Elekid', 'Round Nine Draft Picks'],
  [677, 'Zigzagoon', 'Round Nine Draft Picks'],
  [676, 'Roselia', 'Round Nine Draft Picks'],
  [675, 'Staravia', 'Round Nine Draft Picks'],
  [674, 'Buizel', 'Round Nine Draft Picks'],
  [673, 'Drilbur', 'Round Nine Draft Picks'],
  [672, 'Trubbish', 'Round Nine Draft Picks'],
  [671, 'Minccino', 'Round Nine Draft Picks'],
  [670, 'Rufflet', 'Round Nine Draft Picks'],
  [669, 'Caterpie', 'Round Nine Draft Picks'],
  [668, 'Archen', 'Round Nine Draft Picks'],
  [667, 'Vanillish', 'Round Nine Draft Picks'],
  [666, 'Cutiefly', 'Round Nine Draft Picks'],
  [665, 'Quilava', 'Round Nine Draft Picks'],
  [664, 'Sealeo', 'Round Nine Draft Picks'],
  [663, 'Bronzor', 'Round Nine Draft Picks'],
  [662, 'Sharpedo', 'Round Nine Draft Picks'],
  [661, 'Drapion', 'Round Nine Draft Picks'],
  [660, 'Shellos East Sea', 'Round Nine Draft Picks'],
  // I Do One Thing, But Maybe I Shouldn't
  [659, 'Dudunsparce', "I Do One Thing, But Maybe I Shouldn't"],
  [658, 'Comfey', "I Do One Thing, But Maybe I Shouldn't"],
  [657, 'Drednaw', "I Do One Thing, But Maybe I Shouldn't"],
  [656, 'Sandaconda', "I Do One Thing, But Maybe I Shouldn't"],
  [655, 'Pawmo', "I Do One Thing, But Maybe I Shouldn't"],
  [654, 'Greavard', "I Do One Thing, But Maybe I Shouldn't"],
  [653, 'Obstagoon', "I Do One Thing, But Maybe I Shouldn't"],
  [652, 'Emolga', "I Do One Thing, But Maybe I Shouldn't"],
  [651, 'Hoopa Confined', "I Do One Thing, But Maybe I Shouldn't"],
  [650, 'Meowth Galarian Form', "I Do One Thing, But Maybe I Shouldn't"],
  [649, 'Quaxly', "I Do One Thing, But Maybe I Shouldn't"],
  [648, 'Arctovish', "I Do One Thing, But Maybe I Shouldn't"],
  [647, 'Stunfisk Galarian Form', "I Do One Thing, But Maybe I Shouldn't"],
  [646, 'Tauros Paldean Combat Breed', "I Do One Thing, But Maybe I Shouldn't"],
  [645, 'Sneasel Hisuian Form', "I Do One Thing, But Maybe I Shouldn't"],
  [644, 'Flapple', "I Do One Thing, But Maybe I Shouldn't"],
  [643, 'Zubat', "I Do One Thing, But Maybe I Shouldn't"],
  [642, 'Paras', "I Do One Thing, But Maybe I Shouldn't"],
  [641, 'Tentacool', "I Do One Thing, But Maybe I Shouldn't"],
  [640, 'Slowpoke Galarian Form', "I Do One Thing, But Maybe I Shouldn't"],
  [639, 'Dewgong', "I Do One Thing, But Maybe I Shouldn't"],
  [638, 'Staryu', "I Do One Thing, But Maybe I Shouldn't"],
  [637, 'Necrozma', "I Do One Thing, But Maybe I Shouldn't"],
  [636, 'Pinsir', "I Do One Thing, But Maybe I Shouldn't"],
  [635, 'Wooper Paldean Form', "I Do One Thing, But Maybe I Shouldn't"],
  [634, 'Delcatty', "I Do One Thing, But Maybe I Shouldn't"],
  [633, 'Relicanth', "I Do One Thing, But Maybe I Shouldn't"],
  [632, 'Beldum', "I Do One Thing, But Maybe I Shouldn't"],
  [631, 'Grotle', "I Do One Thing, But Maybe I Shouldn't"],
  [630, 'Luxio', "I Do One Thing, But Maybe I Shouldn't"],
  [629, 'Sandile', "I Do One Thing, But Maybe I Shouldn't"],
  [628, 'Joltik', "I Do One Thing, But Maybe I Shouldn't"],
  [627, 'Cryogonal', "I Do One Thing, But Maybe I Shouldn't"],
  [626, 'Stunfisk', "I Do One Thing, But Maybe I Shouldn't"],
  [625, 'Durant', "I Do One Thing, But Maybe I Shouldn't"],
  [624, 'Spewpa', "I Do One Thing, But Maybe I Shouldn't"],
  [623, 'Crawdaunt', "I Do One Thing, But Maybe I Shouldn't"],
  [622, 'Florges (all forms)', "I Do One Thing, But Maybe I Shouldn't"],
  [621, 'Brionne', "I Do One Thing, But Maybe I Shouldn't"],
  [620, 'Toxapex', "I Do One Thing, But Maybe I Shouldn't"],
  [619, 'Scorbunny', "I Do One Thing, But Maybe I Shouldn't"],
  [618, 'Sliggoo', "I Do One Thing, But Maybe I Shouldn't"],
  [617, 'Horsea', "I Do One Thing, But Maybe I Shouldn't"],
  [616, 'Wooloo', "I Do One Thing, But Maybe I Shouldn't"],
  [615, 'Voltorb', "I Do One Thing, But Maybe I Shouldn't"],
  [614, 'Iron Boulder', "I Do One Thing, But Maybe I Shouldn't"],
  [613, 'Type: Null', "I Do One Thing, But Maybe I Shouldn't"],
  [612, 'Cramorant', "I Do One Thing, But Maybe I Shouldn't"],
  [611, 'Bidoof', "I Do One Thing, But Maybe I Shouldn't"],
  [610, 'Venonat', "I Do One Thing, But Maybe I Shouldn't"],
  [609, 'Poliwhirl', "I Do One Thing, But Maybe I Shouldn't"],
  [608, 'Cyndaquil', "I Do One Thing, But Maybe I Shouldn't"],
  [607, 'Flaafy', "I Do One Thing, But Maybe I Shouldn't"],
  [606, 'Wingull', "I Do One Thing, But Maybe I Shouldn't"],
  // Excited Until You Use It
  [605, 'Eiscue', 'Excited Until You Use It'],
  [604, 'Slurpuff', 'Excited Until You Use It'],
  [603, 'Cacturne', 'Excited Until You Use It'],
  [602, 'Mr. Rime', 'Excited Until You Use It'],
  [601, 'Kecleon', 'Excited Until You Use It'],
  [600, 'Croagunk', 'Excited Until You Use It'],
  [599, 'Darumaka', 'Excited Until You Use It'],
  [598, 'Sigilyph', 'Excited Until You Use It'],
  [597, 'Larvesta', 'Excited Until You Use It'],
  [596, 'Dewpider', 'Excited Until You Use It'],
  [595, 'Mismagius', 'Excited Until You Use It'],
  [594, 'Banette', 'Excited Until You Use It'],
  [593, 'Calyrex', 'Excited Until You Use It'],
  [592, 'Rapidash', 'Excited Until You Use It'],
  [591, 'Rampardos', 'Excited Until You Use It'],
  [590, 'Hitmonlee', 'Excited Until You Use It'],
  [589, 'Bibarel', 'Excited Until You Use It'],
  [588, 'Seadra', 'Excited Until You Use It'],
  [587, 'Ralts', 'Excited Until You Use It'],
  [586, 'Tangela', 'Excited Until You Use It'],
  [585, 'Misdreavus', 'Excited Until You Use It'],
  [584, 'Celebi', 'Excited Until You Use It'],
  [583, 'Seviper', 'Excited Until You Use It'],
  [582, 'Cradily', 'Excited Until You Use It'],
  [581, 'Bagon', 'Excited Until You Use It'],
  [580, 'Vespiquen', 'Excited Until You Use It'],
  [579, 'Drifloon', 'Excited Until You Use It'],
  [578, 'Froslass', 'Excited Until You Use It'],
  [577, 'Tepig', 'Excited Until You Use It'],
  [576, 'Chimchar', 'Excited Until You Use It'],
  [575, 'Kirlia', 'Excited Until You Use It'],
  [574, 'Swadloon', 'Excited Until You Use It'],
  [573, 'Golbat', 'Excited Until You Use It'],
  [572, 'Darumaka Galarian Form', 'Excited Until You Use It'],
  [571, 'Wigglytuff', 'Excited Until You Use It'],
  // Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation
  [570, 'Foongus', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [569, 'Cyclizar', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [568, 'Litwick', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [567, 'Pawniard', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [566, 'Vullaby', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [565, 'Revavroom', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [564, 'Espurr', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [563, 'Aurorus', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [562, 'Rowlet', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [561, 'Lycanroc Midnight Form', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [560, 'Thwackey', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [559, 'Raboot', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [558, 'Fuecoco', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [557, 'Lokix', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [556, 'Scovillain', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [555, 'Tinkatuff', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [554, 'Houndstone', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [553, 'Hattrem', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [552, 'Rabsca', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [551, 'Hippowdon', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [550, 'Magmortar', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [549, 'Grookey', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [548, 'Orbeetle', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [547, 'Duosion', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [546, 'Morpeko', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [545, 'Dugtrio', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [544, 'Poltchageist', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  [543, 'Tandemaus', "Little Cup Heroes / I'm Not Like Other Girls / Modes of Transportation"],
  // Your Mom Might Know
  [542, "Farfetch'd Galarian Form", 'Your Mom Might Know'],
  [541, 'Floragato', 'Your Mom Might Know'],
  [540, 'Jynx', 'Your Mom Might Know'],
  [539, 'Lampent', 'Your Mom Might Know'],
  [538, "Oricorio Pa'u Style", 'Your Mom Might Know'],
  [537, 'Bewear', 'Your Mom Might Know'],
  [536, 'Medicham', 'Your Mom Might Know'],
  [535, 'Onix', 'Your Mom Might Know'],
  [534, 'Musharna', 'Your Mom Might Know'],
  [533, 'Kabuto', 'Your Mom Might Know'],
  [532, 'Poliwrath', 'Your Mom Might Know'],
  [531, 'Mightyena', 'Your Mom Might Know'],
  [530, 'Shiftry', 'Your Mom Might Know'],
  [529, 'Turtwig', 'Your Mom Might Know'],
  [528, 'Runerigus', 'Your Mom Might Know'],
  [527, 'Kricketune', 'Your Mom Might Know'],
  [526, 'Abomasnow', 'Your Mom Might Know'],
  [525, 'Audino', 'Your Mom Might Know'],
  [524, 'Carracosta', 'Your Mom Might Know'],
  [523, 'Popplio', 'Your Mom Might Know'],
  [522, 'Lurantis', 'Your Mom Might Know'],
  [521, 'Swellow', 'Your Mom Might Know'],
  [520, 'Cosmog', 'Your Mom Might Know'],
  [519, 'Dreepy', 'Your Mom Might Know'],
  [518, 'Sudowoodo', 'Your Mom Might Know'],
  [517, 'Flamigo', 'Your Mom Might Know'],
  [516, 'Treecko', 'Your Mom Might Know'],
  [515, 'Goomy', 'Your Mom Might Know'],
  [514, 'Arbok', 'Your Mom Might Know'],
  [513, 'Electrode Hisuian Form', 'Your Mom Might Know'],
  [512, 'Koffing', 'Your Mom Might Know'],
  [511, 'Tauros Kanto Form', 'Your Mom Might Know'],
  [510, 'Tropius', 'Your Mom Might Know'],
  [509, 'Iron Leaves', 'Your Mom Might Know'],
  [508, 'Iron Thorns', 'Your Mom Might Know'],
  [507, 'Yanmega', 'Your Mom Might Know'],
  [506, 'Gourgeist', 'Your Mom Might Know'],
  [505, 'Oranguru', 'Your Mom Might Know'],
  [504, 'Mr. Mime', 'Your Mom Might Know'],
  [503, 'Mesprit', 'Your Mom Might Know'],
  [502, 'Beedrill', 'Your Mom Might Know'],
  [501, 'Monferno', 'Your Mom Might Know'],
  [500, 'Kadabra', 'Your Mom Might Know'],
  [499, 'Torchic', 'Your Mom Might Know'],
  [498, 'Vulpix', 'Your Mom Might Know'],
  [497, 'Prinplup', 'Your Mom Might Know'],
  [496, 'Cubone', 'Your Mom Might Know'],
  [495, 'Vulpix Alolan Form', 'Your Mom Might Know'],
  // My Mom Definitely Doesn't Know
  [494, 'Fezandipiti', "My Mom Definitely Doesn't Know"],
  [493, 'Drakloak', "My Mom Definitely Doesn't Know"],
  [492, 'Krokorok', "My Mom Definitely Doesn't Know"],
  [491, 'Golurk', "My Mom Definitely Doesn't Know"],
  [490, 'Doublade', "My Mom Definitely Doesn't Know"],
  [489, 'Trevenant', "My Mom Definitely Doesn't Know"],
  [488, 'Oricorio Baile Style', "My Mom Definitely Doesn't Know"],
  [487, 'Oricorio Pom-Pom Style', "My Mom Definitely Doesn't Know"],
  [486, 'Oricorio Sensu Style', "My Mom Definitely Doesn't Know"],
  [485, 'Mudsdale', "My Mom Definitely Doesn't Know"],
  [484, 'Gothorita', "My Mom Definitely Doesn't Know"],
  [483, 'Sprigatito', "My Mom Definitely Doesn't Know"],
  [482, 'Brambleghast', "My Mom Definitely Doesn't Know"],
  [481, 'Stoutland', "My Mom Definitely Doesn't Know"],
  [480, 'Garbodor', "My Mom Definitely Doesn't Know"],
  [479, 'Cetitan', "My Mom Definitely Doesn't Know"],
  [478, 'Bastiodon', "My Mom Definitely Doesn't Know"],
  [477, 'Glastrier', "My Mom Definitely Doesn't Know"],
  [476, "Sirfetch'd", "My Mom Definitely Doesn't Know"],
  [475, 'Aggron', "My Mom Definitely Doesn't Know"],
  [474, 'Electivire', "My Mom Definitely Doesn't Know"],
  [473, 'Zorua Hisuian Form', "My Mom Definitely Doesn't Know"],
  [472, 'Chesnaught', "My Mom Definitely Doesn't Know"],
  [471, 'Slowking Galarian Form', "My Mom Definitely Doesn't Know"],
  [470, 'Drampa', "My Mom Definitely Doesn't Know"],
  [469, 'Polteageist', "My Mom Definitely Doesn't Know"],
  // C-List Celebs
  [468, 'Honchkrow', 'C-List Celebs'],
  [467, 'Omanyte', 'C-List Celebs'],
  [466, 'Sceptile', 'C-List Celebs'],
  [465, 'Marshtomp', 'C-List Celebs'],
  [464, 'Feebas', 'C-List Celebs'],
  [463, 'Azelf', 'C-List Celebs'],
  [462, 'Furret', 'C-List Celebs'],
  [461, 'Luxray', 'C-List Celebs'],
  [460, 'Jigglypuff', 'C-List Celebs'],
  [459, 'Rhyhorn', 'C-List Celebs'],
  [458, 'Manaphy', 'C-List Celebs'],
  // Weirdos (Affectionately)
  [457, 'Okidogi', 'Weirdos (Affectionately)'],
  [456, 'Enamorus Incarnate Form', 'Weirdos (Affectionately)'],
  [455, 'Wyrdeer', 'Weirdos (Affectionately)'],
  [454, 'Iron Moth', 'Weirdos (Affectionately)'],
  [453, 'Braviary Hisuian Form', 'Weirdos (Affectionately)'],
  [452, 'Inteleon', 'Weirdos (Affectionately)'],
  [451, 'Braixen', 'Weirdos (Affectionately)'],
  [450, 'Clawitzer', 'Weirdos (Affectionately)'],
  [449, 'Diancie', 'Weirdos (Affectionately)'],
  [448, 'Deino', 'Weirdos (Affectionately)'],
  [447, 'Eelektross', 'Weirdos (Affectionately)'],
  [446, 'Litten', 'Weirdos (Affectionately)'],
  [445, 'Kilowattrel', 'Weirdos (Affectionately)'],
  [444, 'Bellibolt', 'Weirdos (Affectionately)'],
  [443, 'Kleavor', 'Weirdos (Affectionately)'],
  [442, 'Hoopa Unbound', 'Weirdos (Affectionately)'],
  [441, 'Togetic', 'Weirdos (Affectionately)'],
  [440, 'Heracross', 'Weirdos (Affectionately)'],
  [439, 'Skarmory', 'Weirdos (Affectionately)'],
  [438, 'Altaria', 'Weirdos (Affectionately)'],
  [437, 'Ribombee', 'Weirdos (Affectionately)'],
  [436, 'Clodsire', 'Weirdos (Affectionately)'],
  [435, 'Spheal', 'Weirdos (Affectionately)'],
  // Trying to Be Cool
  [434, 'Pecharunt', 'Trying to Be Cool'],
  [433, 'Meowth Alolan Form', 'Trying to Be Cool'],
  [432, 'Snivy', 'Trying to Be Cool'],
  [431, 'Dewott', 'Trying to Be Cool'],
  [430, 'Tauros Paldean Blaze Breed', 'Trying to Be Cool'],
  [429, 'Centiskorch', 'Trying to Be Cool'],
  [428, 'Pidgeot', 'Trying to Be Cool'],
  [427, 'Vileplume', 'Trying to Be Cool'],
  [426, 'Zygarde 10% Form', 'Trying to Be Cool'],
  [425, 'Purrloin', 'Trying to Be Cool'],
  [424, 'Magneton', 'Trying to Be Cool'],
  [423, 'Meganium', 'Trying to Be Cool'],
  [422, 'Mareep', 'Trying to Be Cool'],
  [421, 'Bellossom', 'Trying to Be Cool'],
  [420, 'Floatzel', 'Trying to Be Cool'],
  [419, 'Gible', 'Trying to Be Cool'],
  [418, 'Munchlax', 'Trying to Be Cool'],
  [417, 'Tangrowth', 'Trying to Be Cool'],
  [416, 'Oshawott', 'Trying to Be Cool'],
  [415, 'Mienfoo', 'Trying to Be Cool'],
  [414, 'Sliggoo Hisuian Form', 'Trying to Be Cool'],
  [413, 'Togedemaru', 'Trying to Be Cool'],
  [412, 'Wobbuffet', 'Trying to Be Cool'],
  [411, 'Iron Crown', 'Trying to Be Cool'],
  [410, 'Absol', 'Trying to Be Cool'],
  [409, 'Kabutops', 'Trying to Be Cool'],
  [408, 'Zeraora', 'Trying to Be Cool'],
  [407, 'Leavanny', 'Trying to Be Cool'],
  [406, 'Zorua', 'Trying to Be Cool'],
  [405, 'Decidueye', 'Trying to Be Cool'],
  [404, 'Iron Jugulis', 'Trying to Be Cool'],
  [403, 'Malamar', 'Trying to Be Cool'],
  [402, 'Steelix', 'Trying to Be Cool'],
  [401, 'Wooper', 'Trying to Be Cool'],
  [400, 'Zweilous', 'Trying to Be Cool'],
  [399, 'Kyurem', 'Trying to Be Cool'],
  [398, 'Quaquaval', 'Trying to Be Cool'],
  [397, 'Persian', 'Trying to Be Cool'],
  [396, 'Slowbro Galarian Form', 'Trying to Be Cool'],
  [395, 'Decidueye Hisuian Form', 'Trying to Be Cool'],
  [394, 'Cloyster', 'Trying to Be Cool'],
  [393, 'Electrode', 'Trying to Be Cool'],
  [392, 'Tauros Paldean Aqua Breed', 'Trying to Be Cool'],
  [391, 'Meowstic Male', 'Trying to Be Cool'],
  [390, 'Zapdos Galarian Form', 'Trying to Be Cool'],
  [389, 'Dratini', 'Trying to Be Cool'],
  [388, 'Salazzle', 'Trying to Be Cool'],
  [387, 'Cleffa', 'Trying to Be Cool'],
  [386, 'Shelgon', 'Trying to Be Cool'],
  [385, 'Seismitoad', 'Trying to Be Cool'],
  [384, 'Scolipede', 'Trying to Be Cool'],
  [383, 'Haxorus', 'Trying to Be Cool'],
  [382, 'Dragalge', 'Trying to Be Cool'],
  [381, 'Hawlucha', 'Trying to Be Cool'],
  [380, 'Goodra', 'Trying to Be Cool'],
  [379, 'Klefki', 'Trying to Be Cool'],
  [378, 'Lycanroc Dusk Form', 'Trying to Be Cool'],
  [377, 'Alakazam', 'Trying to Be Cool'],
  [376, 'Slowpoke', 'Trying to Be Cool'],
  [375, 'Wailord', 'Trying to Be Cool'],
  [374, 'Snom', 'Trying to Be Cool'],
  // I've Made the Pokémon Company So Much Money
  [373, 'Rotom', "I've Made the Pokémon Company So Much Money"],
  [372, 'Appletun', "I've Made the Pokémon Company So Much Money"],
  [371, 'Enamorus Therian Form', "I've Made the Pokémon Company So Much Money"],
  [370, 'Slither Wing', "I've Made the Pokémon Company So Much Money"],
  [369, 'Vikabolt', "I've Made the Pokémon Company So Much Money"],
  [368, 'Cottonee', "I've Made the Pokémon Company So Much Money"],
  [367, 'Lopunny', "I've Made the Pokémon Company So Much Money"],
  [366, 'Omastar', "I've Made the Pokémon Company So Much Money"],
  [365, 'Growlithe Hisuian Form', "I've Made the Pokémon Company So Much Money"],
  [364, 'Gastly', "I've Made the Pokémon Company So Much Money"],
  [363, 'Feraligatr', "I've Made the Pokémon Company So Much Money"],
  [362, 'Nidoqueen', "I've Made the Pokémon Company So Much Money"],
  [361, "Farfetch'd", "I've Made the Pokémon Company So Much Money"],
  [360, 'Muk Alolan Form', "I've Made the Pokémon Company So Much Money"],
  [359, 'Marowak', "I've Made the Pokémon Company So Much Money"],
  [358, 'Starmie', "I've Made the Pokémon Company So Much Money"],
  [357, 'Shuckle', "I've Made the Pokémon Company So Much Money"],
  [356, 'Walrein', "I've Made the Pokémon Company So Much Money"],
  [355, 'Mudkip', "I've Made the Pokémon Company So Much Money"],
  [354, 'Squirtle', "I've Made the Pokémon Company So Much Money"],
  [353, 'Bulbasaur', "I've Made the Pokémon Company So Much Money"],
  // Potential Man
  [352, 'Samurott Hisuian Form', 'Potential Man'],
  [351, 'Goodra Hisuian Form', 'Potential Man'],
  [350, 'Braviary', 'Potential Man'],
  [349, 'Tornadus Therian Form', 'Potential Man'],
  [348, 'Vanilluxe', 'Potential Man'],
  [347, 'Galvantula', 'Potential Man'],
  [346, 'Meloetta Aria Form', 'Potential Man'],
  [345, 'Silvally', 'Potential Man'],
  [344, 'Guzzlord', 'Potential Man'],
  [343, 'Naganadel', 'Potential Man'],
  [342, 'Melmetal', 'Potential Man'],
  [341, 'Frosmoth', 'Potential Man'],
  [340, 'Duraludon', 'Potential Man'],
  [339, 'Uxie', 'Potential Man'],
  [338, 'Spiritomb', 'Potential Man'],
  [337, 'Psyduck', 'Potential Man'],
  [336, 'Drifblim', 'Potential Man'],
  // Beat the Potential Man Allegations
  [335, 'Zygarde Complete Form', 'Beat the Potential Man Allegations'],
  [334, 'Spectrier', 'Beat the Potential Man Allegations'],
  [333, 'Toxicroak', 'Beat the Potential Man Allegations'],
  [332, 'Espathra', 'Beat the Potential Man Allegations'],
  [331, 'Orthworm', 'Beat the Potential Man Allegations'],
  [330, 'Clefable', 'Beat the Potential Man Allegations'],
  [329, 'Parasect', 'Beat the Potential Man Allegations'],
  [328, 'Machamp', 'Beat the Potential Man Allegations'],
  // (Unnamed)
  [327, 'Articuno Galarian Form', 'Top Picks'],
  [326, 'Arctozolt', 'Top Picks'],
  [325, 'Lycanroc Midday Form', 'Top Picks'],
  [324, 'Cobalion', 'Top Picks'],
  [323, 'Virizion', 'Top Picks'],
  [322, 'Slaking', 'Top Picks'],
  [321, 'Glaceon', 'Top Picks'],
  [320, 'Gliscor', 'Top Picks'],
  [319, 'Samurott', 'Top Picks'],
  [318, 'Keldeo Ordinary Form', 'Top Picks'],
  [317, 'Wishiwashi School Form', 'Top Picks'],
  [316, 'Blacephalon', 'Top Picks'],
  [315, 'Toxtricity Low Key Form', 'Top Picks'],
  [314, 'Toxtricity Amped Form', 'Top Picks'],
  [313, 'Dachsbun', 'Top Picks'],
  [312, 'Arboliva', 'Top Picks'],
  [311, 'Toedscool', 'Top Picks'],
  [310, 'Great Tusk', 'Top Picks'],
  [309, 'Sneasel', 'Top Picks'],
  [308, 'Leafeon', 'Top Picks'],
  [307, 'Typhlosion', 'Top Picks'],
  [306, 'Charmander', 'Top Picks'],
  [305, 'Sandy Shocks', 'Top Picks'],
  [304, 'Marshadow', 'Top Picks'],
  [303, 'Archeops', 'Top Picks'],
  [302, 'Hariyama', 'Top Picks'],
  [301, 'Marill', 'Top Picks'],
  [300, 'Golduck', 'Top Picks'],
  [299, 'Pichu', 'Top Picks'],
  [298, 'Gabite', 'Top Picks'],
  [297, 'Cinccino', 'Top Picks'],
  [296, 'Meowth', 'Top Picks'],
  [295, 'Magikarp', 'Top Picks'],
  [294, 'Trapinch', 'Top Picks'],
  [293, 'Piplup', 'Top Picks'],
  // In It to Win It / People Would Commit Felonies
  [292, 'Noivern', 'In It to Win It'],
  [291, 'Torracat', 'In It to Win It'],
  [290, 'Accelgor', 'In It to Win It'],
  [289, 'Iron Treads', 'In It to Win It'],
  [288, 'Tsareena', 'In It to Win It'],
  [287, 'Ampharos', 'In It to Win It'],
  [286, 'Torterra', 'In It to Win It'],
  [285, 'Scraggy', 'In It to Win It'],
  [284, 'Growlithe', 'In It to Win It'],
  [283, 'Charmeleon', 'In It to Win It'],
  [282, 'Wartortle', 'In It to Win It'],
  [281, 'Bisharp', 'In It to Win It'],
  [280, 'Raichu Alolan Form', 'In It to Win It'],
  [279, 'Victreebel', 'In It to Win It'],
  [278, 'Weezing', 'In It to Win It'],
  [277, 'Moltres', 'In It to Win It'],
  [276, 'Dragonair', 'In It to Win It'],
  [275, 'Metang', 'In It to Win It'],
  [274, 'Regice', 'In It to Win It'],
  [273, 'Liepard', 'In It to Win It'],
  [272, 'Zekrom', 'In It to Win It'],
  [271, 'Keldeo Resolute Form', 'In It to Win It'],
  [270, 'Delphox', 'In It to Win It'],
  [269, 'Golisopod', 'In It to Win It'],
  [268, 'Reuniclus', 'In It to Win It'],
  [267, 'Solgaleo', 'In It to Win It'],
  [266, 'Staraptor', 'In It to Win It'],
  [265, 'Pheromosa', 'In It to Win It'],
  [264, 'Togepi', 'In It to Win It'],
  [263, 'Ninetales', 'In It to Win It'],
  [262, 'Slowking', 'In It to Win It'],
  [261, 'Quagsire', 'In It to Win It'],
  [260, 'Zoroark', 'In It to Win It'],
  [259, 'Buzzwole', 'In It to Win It'],
  [258, 'Manectric', 'In It to Win It'],
  [257, 'Rhyperior', 'In It to Win It'],
  [256, 'Tentacruel', 'In It to Win It'],
  [255, 'Mew', 'In It to Win It'],
  [254, 'Blissey', 'In It to Win It'],
  [253, 'Roserade', 'In It to Win It'],
  [252, 'Grovyle', 'In It to Win It'],
  [251, 'Flareon', 'In It to Win It'],
  [250, 'Ivysaur', 'In It to Win It'],
  // You Really Can Win With Your Favorites
  [249, 'Gastrodon West Sea', 'You Really Can Win With Your Favorites'],
  [248, 'Riolu', 'You Really Can Win With Your Favorites'],
  [247, 'Kyurem Black Form', 'You Really Can Win With Your Favorites'],
  [246, 'Magearna', 'You Really Can Win With Your Favorites'],
  [245, 'Alcremie (all forms)', 'You Really Can Win With Your Favorites'],
  [244, 'Hydrapple', 'You Really Can Win With Your Favorites'],
  [243, 'Emboar', 'You Really Can Win With Your Favorites'],
  [242, 'Cofagrigus', 'You Really Can Win With Your Favorites'],
  [241, 'Weavile', 'You Really Can Win With Your Favorites'],
  [240, 'Genesect', 'You Really Can Win With Your Favorites'],
  [239, 'Bronzong', 'You Really Can Win With Your Favorites'],
  [238, 'Camerupt', 'You Really Can Win With Your Favorites'],
  [237, 'Magnezone', 'You Really Can Win With Your Favorites'],
  [236, 'Lilligant', 'You Really Can Win With Your Favorites'],
  [235, 'Lilligant Hisuian Form', 'You Really Can Win With Your Favorites'],
  [234, 'Krookodile', 'You Really Can Win With Your Favorites'],
  [233, 'Darmanitan', 'You Really Can Win With Your Favorites'],
  [232, 'Iron Valiant', 'You Really Can Win With Your Favorites'],
  [231, 'Rhydon', 'You Really Can Win With Your Favorites'],
  [230, 'Typhlosion Hisuian Form', 'You Really Can Win With Your Favorites'],
  [229, 'Deoxys Defense Form', 'You Really Can Win With Your Favorites'],
  [228, 'Deoxys Normal Form', 'You Really Can Win With Your Favorites'],
  [227, 'Mamoswine', 'You Really Can Win With Your Favorites'],
  [226, 'Rotom Fan Form', 'You Really Can Win With Your Favorites'],
  [225, 'Victini', 'You Really Can Win With Your Favorites'],
  [224, 'Cinderace', 'You Really Can Win With Your Favorites'],
  [223, 'Exeggutor Alolan Form', 'You Really Can Win With Your Favorites'],
  [222, 'Skeledirge', 'You Really Can Win With Your Favorites'],
  [221, 'Garganacl', 'You Really Can Win With Your Favorites'],
  [220, 'Ceruledge', 'You Really Can Win With Your Favorites'],
  [219, 'Weezing Galarian Form', 'You Really Can Win With Your Favorites'],
  [218, 'Persian Alolan Form', 'You Really Can Win With Your Favorites'],
  [217, 'Rotom Frost Form', 'You Really Can Win With Your Favorites'],
  [216, 'Basculegion Female', 'You Really Can Win With Your Favorites'],
  [215, 'Gigalith', 'You Really Can Win With Your Favorites'],
  [214, 'Sableye', 'You Really Can Win With Your Favorites'],
  // I Make YouTube Shorts When They Win
  [213, 'Thundurus Therian Form', 'I Make YouTube Shorts When They Win'],
  [212, 'Overqwil', 'I Make YouTube Shorts When They Win'],
  [211, 'Xurkitree', 'I Make YouTube Shorts When They Win'],
  [210, 'Jellicent', 'I Make YouTube Shorts When They Win'],
  [209, 'Mandibuzz', 'I Make YouTube Shorts When They Win'],
  [208, 'Zygarde 50% Form', 'I Make YouTube Shorts When They Win'],
  [207, 'Coalossal', 'I Make YouTube Shorts When They Win'],
  [206, 'Regidrago', 'I Make YouTube Shorts When They Win'],
  [205, 'Toedscruel', 'I Make YouTube Shorts When They Win'],
  [204, 'Iron Bundle', 'I Make YouTube Shorts When They Win'],
  [203, 'Sinistcha', 'I Make YouTube Shorts When They Win'],
  [202, 'Scream Tail', 'I Make YouTube Shorts When They Win'],
  [201, 'Raikou', 'I Make YouTube Shorts When They Win'],
  [200, 'Lugia', 'I Make YouTube Shorts When They Win'],
  [199, 'Electabuzz', 'I Make YouTube Shorts When They Win'],
  [198, 'Magmar', 'I Make YouTube Shorts When They Win'],
  [197, 'Gothitelle', 'I Make YouTube Shorts When They Win'],
  [196, 'Gastrodon East Sea', 'I Make YouTube Shorts When They Win'],
  [195, 'Wo-Chien', 'I Make YouTube Shorts When They Win'],
  [194, 'Pelipper', 'I Make YouTube Shorts When They Win'],
  [193, 'Breloom', 'I Make YouTube Shorts When They Win'],
  [192, 'Indeedee Male', 'I Make YouTube Shorts When They Win'],
  [191, 'Jumpluff', 'I Make YouTube Shorts When They Win'],
  [190, 'Brute Bonnet', 'I Make YouTube Shorts When They Win'],
  [189, 'Kyurem White Form', 'I Make YouTube Shorts When They Win'],
  [188, 'Regirock', 'I Make YouTube Shorts When They Win'],
  [187, 'Giratina Altered Form', 'I Make YouTube Shorts When They Win'],
  [186, 'Gallade', 'I Make YouTube Shorts When They Win'],
  [185, 'Darmanitan Galarian Form', 'I Make YouTube Shorts When They Win'],
  [184, 'Escavalier', 'I Make YouTube Shorts When They Win'],
  [183, 'Ferrothorn', 'I Make YouTube Shorts When They Win'],
  [182, 'Vivillon (all forms)', 'I Make YouTube Shorts When They Win'],
  [181, 'Zoroark Hisuian Form', 'I Make YouTube Shorts When They Win'],
  [180, 'Araquanid', 'I Make YouTube Shorts When They Win'],
  [179, 'Grimmsnarl', 'I Make YouTube Shorts When They Win'],
  [178, 'Dracozolt', 'I Make YouTube Shorts When They Win'],
  [177, 'Walking Wake', 'I Make YouTube Shorts When They Win'],
  [176, 'Nidoking', 'I Make YouTube Shorts When They Win'],
  [175, 'Ninetales Alolan Form', 'I Make YouTube Shorts When They Win'],
  [174, 'Torkoal', 'I Make YouTube Shorts When They Win'],
  [173, 'Lapras', 'I Make YouTube Shorts When They Win'],
  [172, 'Jolteon', 'I Make YouTube Shorts When They Win'],
  [171, 'Moltres Galarian Form', 'I Make YouTube Shorts When They Win'],
  [170, 'Espeon', 'I Make YouTube Shorts When They Win'],
  [169, 'Slowbro', 'I Make YouTube Shorts When They Win'],
  [168, 'Blastoise', 'I Make YouTube Shorts When They Win'],
  [167, 'Scyther', 'I Make YouTube Shorts When They Win'],
  // Good Pokémon With Great Designs
  [166, 'Tapu Bulu', 'Good Pokémon With Great Designs'],
  [165, 'Eternatus', 'Good Pokémon With Great Designs'],
  [164, 'Flygon', 'Good Pokémon With Great Designs'],
  [163, 'Regigigas', 'Good Pokémon With Great Designs'],
  [162, 'Shaymin Land Form', 'Good Pokémon With Great Designs'],
  [161, 'Serperior', 'Good Pokémon With Great Designs'],
  [160, 'Conkeldurr', 'Good Pokémon With Great Designs'],
  [159, 'Hitmontop', 'Good Pokémon With Great Designs'],
  [158, 'Pawmot', 'Good Pokémon With Great Designs'],
  [157, 'Basculegion Male', 'Good Pokémon With Great Designs'],
  [156, 'Gouging Fire', 'Good Pokémon With Great Designs'],
  [155, 'Politoed', 'Good Pokémon With Great Designs'],
  [154, 'Crobat', 'Good Pokémon With Great Designs'],
  [153, 'Chansey', 'Good Pokémon With Great Designs'],
  [152, 'Aerodactyl', 'Good Pokémon With Great Designs'],
  [151, 'Ludicolo', 'Good Pokémon With Great Designs'],
  [150, 'Registeel', 'Good Pokémon With Great Designs'],
  [149, 'Porygon-Z', 'Good Pokémon With Great Designs'],
  [148, 'Dialga Origin Form', 'Good Pokémon With Great Designs'],
  [147, 'Mienshao', 'Good Pokémon With Great Designs'],
  [146, 'Porygon', 'Good Pokémon With Great Designs'],
  [145, 'Glimmora', 'Good Pokémon With Great Designs'],
  [144, 'Meowscarada', 'Good Pokémon With Great Designs'],
  [143, 'Empoleon', 'Good Pokémon With Great Designs'],
  [142, 'Haunter', 'Good Pokémon With Great Designs'],
  [141, 'Murkrow', 'Good Pokémon With Great Designs'],
  [140, 'Infernape', 'Good Pokémon With Great Designs'],
  [139, 'Vaporeon', 'Good Pokémon With Great Designs'],
  [138, 'Rotom Mow Form', 'Good Pokémon With Great Designs'],
  [137, 'Giratina Origin Form', 'Good Pokémon With Great Designs'],
  [136, 'Terrakion', 'Good Pokémon With Great Designs'],
  [135, 'Kommo-o', 'Good Pokémon With Great Designs'],
  [134, 'Necrozma Dusk Mane', 'Good Pokémon With Great Designs'],
  [133, 'Necrozma Dawn Wings', 'Good Pokémon With Great Designs'],
  [132, 'Hatterene', 'Good Pokémon With Great Designs'],
  [131, 'Armarouge', 'Good Pokémon With Great Designs'],
  [130, 'Ting-Lu', 'Good Pokémon With Great Designs'],
  [129, 'Marowak Alolan Form', 'Good Pokémon With Great Designs'],
  [128, 'Dusclops', 'Good Pokémon With Great Designs'],
  [127, 'Mewtwo', 'Good Pokémon With Great Designs'],
  [126, 'Exeggutor', 'Good Pokémon With Great Designs'],
  [125, 'Mawile', 'Good Pokémon With Great Designs'],
  // Real Heroes
  [124, 'Palafin', 'Real Heroes'],
  [123, 'Landorus Incarnate Form', 'Real Heroes'],
  [122, 'Azumarill', 'Real Heroes'],
  [121, 'Kingdra', 'Real Heroes'],
  [120, 'Deoxys Attack Form', 'Real Heroes'],
  [119, 'Deoxys Speed Form', 'Real Heroes'],
  [118, 'Excadrill', 'Real Heroes'],
  [117, 'Chandelure', 'Real Heroes'],
  [116, 'Palkia Origin Form', 'Real Heroes'],
  [115, 'Shaymin Sky Form', 'Real Heroes'],
  [114, 'Tinkaton', 'Real Heroes'],
  [113, 'Baxcalibur', 'Real Heroes'],
  [112, 'Roaring Moon', 'Real Heroes'],
  [111, 'Archaludon', 'Real Heroes'],
  [110, 'Indeedee Female', 'Real Heroes'],
  [109, 'Butterfree', 'Real Heroes'],
  [108, 'Dracovish', 'Real Heroes'],
  [107, 'Entei', 'Real Heroes'],
  [106, 'Iron Hands', 'Real Heroes'],
  [105, 'Reshiram', 'Real Heroes'],
  [104, 'Scrafty', 'Real Heroes'],
  [103, 'Corviknight', 'Real Heroes'],
  [102, 'Talonflame', 'Real Heroes'],
  [101, 'Blaziken', 'Real Heroes'],
  // Top 100
  [100, 'Pikachu', 'Top 100'],
  [99, 'Tatsugiri', 'Top 100'],
  [98, 'Arcanine Hisuian Form', 'Top 100'],
  [97, 'Sneasler', 'Top 100'],
  [96, 'Greninja', 'Top 100'],
  [95, 'Jirachi', 'Top 100'],
  [94, 'Dondozo', 'Top 100'],
  [93, 'Tapu Lele', 'Top 100'],
  [92, 'Darkrai', 'Top 100'],
  [91, 'Annihilape', 'Top 100'],
  [90, 'Rotom Heat Form', 'Top 100'],
  [89, 'Kingambit', 'Top 100'],
  [88, 'Articuno', 'Top 100'],
  [87, 'Regieleki', 'Top 100'],
  [86, 'Maushold', 'Top 100'],
  [85, 'Togekiss', 'Top 100'],
  [84, 'Nihilego', 'Top 100'],
  [83, 'Gardevoir', 'Top 100'],
  [82, 'Swampert', 'Top 100'],
  [81, 'Tornadus Incarnate Form', 'Top 100'],
  [80, 'Farigiraf', 'Top 100'],
  [79, 'Clefairy', 'Top 100'],
  [78, 'Heatran', 'Top 100'],
  [77, 'Ursaluna Bloodmoon Form', 'Top 100'],
  [76, 'Terapagos', 'Top 100'],
  [75, 'Pachirisu', 'Top 100'],
  [74, 'Lucario', 'Top 100'],
  [73, 'Scizor', 'Top 100'],
  [72, 'Suicune', 'Top 100'],
  [71, 'Ogerpon Cornerstone Mask', 'Top 100'],
  [70, 'Ho-Oh', 'Top 100'],
  [69, 'Palkia', 'Top 100'],
  [68, 'Kangaskhan', 'Top 100'],
  [67, 'Shedinja', 'Top 100'],
  [66, 'Raichu', 'Top 100'],
  [65, 'Latias', 'Top 100'],
  [64, 'Thundurus Incarnate Form', 'Top 100'],
  [63, 'Aegislash', 'Top 100'],
  [62, 'Yveltal', 'Top 100'],
  [61, 'Gengar', 'Top 100'],
  [60, 'Ditto', 'Top 100'],
  [59, 'Eevee', 'Top 100'],
  [58, 'Dragonite', 'Top 100'],
  [57, 'Celesteela', 'Top 100'],
  [56, 'Urshifu Single Strike Style', 'Top 100'],
  [55, 'Tapu Koko', 'Top 100'],
  [54, 'Gholdengo', 'Top 100'],
  [53, 'Ogerpon Teal Mask', 'Top 100'],
  [52, 'Metagross', 'Top 100'],
  [51, 'Rotom Wash Form', 'Top 100'],
  [50, 'Milotic', 'Top 100'],
  [49, 'Calyrex Ice Rider', 'Top 100'],
  [48, 'Dialga', 'Top 100'],
  [47, 'Kartana', 'Top 100'],
  [46, 'Ursaluna', 'Top 100'],
  [45, 'Chien-Pao', 'Top 100'],
  [44, 'Sylveon', 'Top 100'],
  [43, 'Primarina', 'Top 100'],
  [42, 'Chi-Yu', 'Top 100'],
  [41, 'Ogerpon Wellspring Mask', 'Top 100'],
  [40, 'Ogerpon Hearthflame Mask', 'Top 100'],
  [39, 'Porygon2', 'Top 100'],
  [38, 'Umbreon', 'Top 100'],
  [37, 'Whimsicott', 'Top 100'],
  [36, 'Tapu Fini', 'Top 100'],
  [35, 'Dragapult', 'Top 100'],
  [34, 'Arcanine', 'Top 100'],
  [33, 'Rillaboom', 'Top 100'],
  [32, 'Hydreigon', 'Top 100'],
  // Top 31
  [31, 'Urshifu Rapid Strike Style', 'Top 31'],
  [30, 'Calyrex Shadow Rider', 'Top 31'],
  [29, 'Koraidon', 'Top 31'],
  [28, 'Snorlax', 'Top 31'],
  [27, 'Venusaur', 'Top 31'],
  [26, 'Latios', 'Top 31'],
  [25, 'Zamazenta', 'Top 31'],
  [24, 'Raging Bolt', 'Top 31'],
  [23, 'Volcarona', 'Top 31'],
  [22, 'Gyarados', 'Top 31'],
  [21, 'Zapdos', 'Top 31'],
  [20, 'Stakataka', 'Top 31'],
  [19, 'Flutter Mane', 'Top 31'],
  [18, 'Zacian', 'Top 31'],
  [17, 'Amoonguss', 'Top 31'],
  [16, 'Smeargle', 'Top 31'],
  [15, 'Miraidon', 'Top 31'],
  [14, 'Landorus Therian Form', 'Top 31'],
  [13, 'Tyranitar', 'Top 31'],
  [12, 'Lunala', 'Top 31'],
  [11, 'Arceus', 'Top 31'],
  [10, 'Mimikyu', 'Top 31'],
  [9, 'Salamence', 'Top 31'],
  [8, 'Rayquaza', 'Top 31'],
  [7, 'Garchomp', 'Top 31'],
  [6, 'Xerneas', 'Top 31'],
  [5, 'Cresselia', 'Top 31'],
  [4, 'Incineroar', 'Top 31'],
  [3, 'Charizard', 'Top 31'],
  [2, 'Groudon', 'Top 31'],
  [1, 'Kyogre', 'Top 31'],
];

// Extra overrides for names with special chars or tricky matches
const EXTRA = {
  'nidoran♂': 32,
  'nidoran♀': 29,
  'type: null': 772,
  'type:null': 772,
  'jangmo-o': 782,
  'hakamo-o': 783,
  'kommo-o': 784,
  'ho-oh': 250,
  'porygon-z': 474,
  'chien-pao': 1002,
  'ting-lu': 1003,
  'chi-yu': 1004,
  'wo-chien': 1001,
  "sirfetch'd": 865,
  "farfetch'd": 83,
  'mr. mime': 122,
  'mr. rime': 866,
  'mime jr.': 439,
  'flabébé': 669,
};
// Additional spelling/naming fixes
const SPELLING = {
  'hisuian avalugg':          10243,
  'hisuian qwilfish':         10234,
  'frafure':                  611,   // garbled "Fracture" = Fraxure
  'hattenna':                 856,   // data spells it Hatenna (one t)
  'flaafy':                   180,   // data spells it Flaaffy
  'vikabolt':                 738,   // data spells it Vikavolt
  'tapu koko':                785,
  'tapu lele':                786,
  'tapu bulu':                787,
  'tapu fini':                788,
  'toxtricity amped form':    849,
  'toxtricity low key form':  10184,
};
Object.assign(OVERRIDES, EXTRA, SPELLING);

// Resolve a wolfe name to a pokemon id
function resolve(name) {
  const key = name.toLowerCase().trim();
  if (OVERRIDES[key] !== undefined) return OVERRIDES[key];
  // Direct match
  if (byName[key]) return byName[key].id;
  // Strip " (all forms)" etc
  const stripped = key.replace(/\s*\(.*\)\s*$/, '').trim();
  if (byName[stripped]) return byName[stripped].id;
  return null;
}

// Build output
const output = [];
const unmatched = [];

for (const [rank, name, category] of WOLFE_LIST) {
  const id = resolve(name);
  if (id === null) {
    unmatched.push({ rank, name, category });
  } else {
    output.push({ id, rank, category });
  }
}

const outPath = path.join(__dirname, '../public/data/wolfe-rankings.json');
fs.writeFileSync(outPath, JSON.stringify(output, null, 2));
console.log(`Written ${output.length} entries to ${outPath}`);

if (unmatched.length) {
  console.warn(`\nUNMATCHED (${unmatched.length}):`);
  unmatched.forEach(u => console.warn(`  Rank ${u.rank}: "${u.name}"`));
} else {
  console.log('All entries matched!');
}
